services:
  - type: web
    name: healthcare-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT backend.app:app
    plan: free
    region: singapore # or oregon / frankfurt
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.11"
      - key: CORS_ORIGINS
        value: "*"
      - key: HOST
        value: "0.0.0.0"
