import React from 'react';
import { ShieldCheck, Lock, EyeOff, Database, KeyRound, Server } from 'lucide-react';
import { SEOHelmet } from '../components/SEOHelmet';

export const Privacy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">
      <SEOHelmet
        title="Privacy & Data Protection Policy"
        description="Learn how user data, authentication credentials, and health observations are handled securely in HEALTHCARE."
      />

      {/* Header Banner */}
      <div className="space-y-3 border-b border-slate-200 pb-6">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-teal-100 text-teal-800 text-xs font-semibold">
          <ShieldCheck className="w-3.5 h-3.5 text-teal-600" />
          <span>Data Privacy & Governance</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-display font-extrabold text-slate-900">
          Privacy Policy & Security
        </h1>
        <p className="text-sm text-slate-600">
          Last Updated: March 2025 • Academic & Healthcare Discovery Platform
        </p>
      </div>

      {/* Core Principles */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
        <div className="p-6 rounded-2xl bg-white border border-slate-200 space-y-2">
          <div className="p-2 rounded-xl bg-teal-100 text-teal-800 w-fit">
            <Lock className="w-5 h-5" />
          </div>
          <h3 className="font-bold text-slate-900 text-sm">Data Minimization</h3>
          <p className="text-xs text-slate-600 leading-relaxed">
            We only collect information strictly required to demonstrate remote monitoring and early risk screening features.
          </p>
        </div>

        <div className="p-6 rounded-2xl bg-white border border-slate-200 space-y-2">
          <div className="p-2 rounded-xl bg-sky-100 text-sky-800 w-fit">
            <EyeOff className="w-5 h-5" />
          </div>
          <h3 className="font-bold text-slate-900 text-sm">No Third-Party Sale</h3>
          <p className="text-xs text-slate-600 leading-relaxed">
            Your health observations, questionnaire inputs, and profile data are never sold, monetized, or shared with commercial advertisers.
          </p>
        </div>

        <div className="p-6 rounded-2xl bg-white border border-slate-200 space-y-2">
          <div className="p-2 rounded-xl bg-purple-100 text-purple-800 w-fit">
            <KeyRound className="w-5 h-5" />
          </div>
          <h3 className="font-bold text-slate-900 text-sm">Cognito Security</h3>
          <p className="text-xs text-slate-600 leading-relaxed">
            Passwords are encrypted using industry-standard hashing protocols in Amazon Cognito and are never stored in plaintext.
          </p>
        </div>
      </div>

      {/* Detailed Policy Sections */}
      <div className="bg-white rounded-3xl p-8 border border-slate-200 shadow-xs space-y-6 text-slate-700 text-xs sm:text-sm leading-relaxed">
        <div className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">1. Information We Collect</h2>
          <p>
            When registering on HEALTHCARE, we collect basic identification information: full name, email address, optional contact number, city, state, and user classification (Patient, Student, Healthcare Professional, General User).
          </p>
          <p>
            When using the Remote Patient Monitoring feature, user-entered vital signs (heart rate, blood pressure, glucose, temperature, SpO2, respiratory rate, and weight) are recorded under your authenticated session.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">2. How Data is Processed and Stored</h2>
          <p>
            In the cloud environment, data is stored in partitioned Amazon DynamoDB tables indexed by unique user identifiers. In local standalone mode, data is securely stored within the browser's persistent localStorage store on your device.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">3. Geolocation Data</h2>
          <p>
            Geolocation access is requested on an explicit, opt-in basis via standard browser Geolocation APIs solely for calculating approximate straight-line geodesic distance to NIRF-ranked medical colleges. Coordinates are processed locally and never tracked across external sites.
          </p>
        </div>

        <div className="space-y-2">
          <h2 className="text-base font-bold text-slate-900">4. Prototype & Educational Limitations</h2>
          <p>
            HEALTHCARE is an academic and exploratory discovery tool. Health assessments and telemetry logs generated by this system do not constitute an official Electronic Health Record (EHR) and should not be used as the sole basis for clinical medical treatment.
          </p>
        </div>
      </div>
    </div>
  );
};
